=== chinab/jfcrawler/jfcrawler/template/schema/template.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2010 (http://www.altova.com) by ruKy (406A) -->
<!--W3C Schema generated by XMLSpy v2010 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="vertex">
		<xs:complexType>
			<xs:all>
				<xs:element ref="pattern"/>
				<xs:element ref="script" minOccurs="0"/>
				<xs:element ref="link" minOccurs="0"/>
			</xs:all>
			<xs:attribute name="paging" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="none"/>
						<xs:enumeration value="catalog"/>
						<xs:enumeration value="prev"/>
						<xs:enumeration value="next"/>
						<xs:enumeration value="paging"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="outlink" type="xs:boolean" use="optional"/>
			<xs:attribute name="id" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="article"/>
						<xs:enumeration value="board"/>
						<xs:enumeration value="catalog"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="sites">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="site" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="sitemap">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="vertex" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="site">
		<xs:complexType>
			<xs:attribute name="url" type="xs:anyURI" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="script">
		<xs:complexType>
			<xs:attribute name="xpath" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="regex-item">
		<xs:complexType>
			<xs:attribute name="regex" type="xs:string" use="required"/>
			<xs:attribute name="key" type="xs:string" use="required"/>
			<xs:attribute name="skip" type="xs:int" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="query-item">
		<xs:complexType>
			<xs:attribute name="query" type="xs:string" use="required"/>
			<xs:attribute name="key" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="pattern">
		<xs:complexType>
			<xs:choice minOccurs="0">
				<xs:sequence>
					<xs:element ref="query-item" minOccurs="0" maxOccurs="unbounded"/>
				</xs:sequence>
				<xs:sequence>
					<xs:element ref="regex-item" minOccurs="0" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:choice>
			<xs:attribute name="type" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="regex"/>
						<xs:enumeration value="token"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="token" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="link">
		<xs:complexType>
			<xs:attribute name="xpath" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="forum">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="sites"/>
				<xs:element ref="sitemap"/>
			</xs:sequence>
			<xs:attribute name="id" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="newsmth"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== chinab/jfcrawler/trunk/jfcrawler/template/newsmth.xml
<?xml version="1.0" encoding="UTF-8"?>
<forum id="newsmth" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema/template.xsd">
	<sites>
		<site url="http://www.newsmth.net/bbssec.php"/>
	</sites>
	<sitemap>
		<vertex id="catalog" paging="catalog" outlink="true">
			<script xpath="//SCRIPT/text()"/>
			<pattern type="token" token="bbsboa"/>
		</vertex>
		<vertex id="board" paging="prev" outlink="true">
			<script xpath="//SCRIPT/text()"/>
			<pattern type="token" token="bbsdoc">
				<query-item key="key" query="board"/>
				<query-item key="page" query="page"/>
			</pattern>
		</vertex>
		<vertex id="article" paging="none" outlink="false">
			<pattern type="token" token="bbscon">
				<query-item key="id" query="id"/>
				<query-item key="boardId" query="bid"/>
			</pattern>
		</vertex>
	</sitemap>
</forum>
